export const PERM = {
  SYSTEM: 'system',

  USER: 'system:user',
  USER_VIEW: 'system:user:view',
  USER_LIST: 'system:user:list',
  USER_CREATE: 'system:user:create',
  USER_UPDATE: 'system:user:update',
  USER_DELETE: 'system:user:delete',
  USER_IMPORT: 'system:user:import',
  USER_EXPORT: 'system:user:export',
  USER_RESET_PASSWORD: 'system:user:reset-password',
  USER_UPDATE_ROLES: 'system:user:update-roles',

  ROLE: 'system:role',
  ROLE_VIEW: 'system:role:view',
  ROLE_LIST: 'system:role:list',
  ROLE_CREATE: 'system:role:create',
  ROLE_UPDATE: 'system:role:update',
  ROLE_DELETE: 'system:role:delete',
  ROLE_UPDATE_PERMISSIONS: 'system:role:update-permissions',
  ROLE_UPDATE_USERS: 'system:role:update-users',
  ROLE_UPDATE_DATA_SCOPE: 'system:role:update-data-scope',

  PERMISSION: 'system:permission',
  PERMISSION_VIEW: 'system:permission:view',
  PERMISSION_LIST: 'system:permission:list',
  PERMISSION_CREATE: 'system:permission:create',
  PERMISSION_UPDATE: 'system:permission:update',
  PERMISSION_DELETE: 'system:permission:delete',
  PERMISSION_SCAN: 'system:permission:scan',

  MENU: 'system:menu',
  MENU_VIEW: 'system:menu:view',
  MENU_LIST: 'system:menu:list',
  MENU_CREATE: 'system:menu:create',
  MENU_UPDATE: 'system:menu:update',
  MENU_DELETE: 'system:menu:delete',

  DEPARTMENT: 'system:department',
  DEPARTMENT_VIEW: 'system:department:view',
  DEPARTMENT_LIST: 'system:department:list',
  DEPARTMENT_CREATE: 'system:department:create',
  DEPARTMENT_UPDATE: 'system:department:update',
  DEPARTMENT_DELETE: 'system:department:delete',

  POSITION: 'system:position',
  POSITION_VIEW: 'system:position:view',
  POSITION_LIST: 'system:position:list',
  POSITION_CREATE: 'system:position:create',
  POSITION_UPDATE: 'system:position:update',
  POSITION_DELETE: 'system:position:delete',

  DICTIONARY: 'system:dictionary',
  DICTIONARY_VIEW: 'system:dictionary:view',
  DICTIONARY_LIST: 'system:dictionary:list',
  DICTIONARY_CREATE: 'system:dictionary:create',
  DICTIONARY_UPDATE: 'system:dictionary:update',
  DICTIONARY_DELETE: 'system:dictionary:delete',

  CONFIG: 'system:config',
  CONFIG_VIEW: 'system:config:view',
  CONFIG_LIST: 'system:config:list',
  CONFIG_CREATE: 'system:config:create',
  CONFIG_UPDATE: 'system:config:update',
  CONFIG_DELETE: 'system:config:delete',

  LOG: 'system:log',
  LOG_VIEW: 'system:log:view',
  LOG_DELETE: 'system:log:delete',
  LOG_CLEAN: 'system:log:clean',
  LOG_OPERATION: 'system:log-operation',
  LOG_OPERATION_VIEW: 'system:log-operation:view',
  LOG_OPERATION_LIST: 'system:log-operation:list',
  LOG_OPERATION_DELETE: 'system:log-operation:delete',
  LOG_OPERATION_CLEAN: 'system:log-operation:clean',
  LOG_OPERATION_CLEAR: 'system:log-operation:clear',
  LOG_LOGIN: 'system:log-login',
  LOG_LOGIN_VIEW: 'system:log-login:view',
  LOG_LOGIN_LIST: 'system:log-login:list',
  LOG_LOGIN_DELETE: 'system:log-login:delete',
  LOG_LOGIN_CLEAN: 'system:log-login:clean',
  LOG_LOGIN_CLEAR: 'system:log-login:clear',

  MONITOR: 'monitor',
  MONITOR_SERVER: 'monitor:server',
  MONITOR_SERVER_VIEW: 'monitor:server:view',
  MONITOR_SERVER_LIST: 'monitor:server:list',

  MONITOR_ONLINE_USER: 'monitor:online-user',
  MONITOR_ONLINE_USER_VIEW: 'monitor:online-user:view',
  MONITOR_ONLINE_USER_LIST: 'monitor:online-user:list',
  MONITOR_ONLINE_USER_KICK: 'monitor:online-user:kick',

  MONITOR_CACHE: 'monitor:cache',
  MONITOR_CACHE_VIEW: 'monitor:cache:view',
  MONITOR_CACHE_LIST: 'monitor:cache:list',
  MONITOR_CACHE_CLEAR: 'monitor:cache:clear',
} as const;

export type PermKey = (typeof PERM)[keyof typeof PERM];
