import {
  AlipayCircleFilled,
  ApiOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowUpOutlined,
  BellOutlined,
  BugOutlined,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseCircleFilled,
  CloseCircleOutlined,
  CloseOutlined,
  CopyOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DownOutlined,
  EditOutlined,
  ExclamationCircleFilled,
  ExclamationCircleOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  EyeTwoTone,
  FieldTimeOutlined,
  FileTextOutlined,
  FolderOutlined,
  GithubFilled,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LayoutOutlined,
  LeftOutlined,
  LockOutlined,
  LoginOutlined,
  MailOutlined,
  MobileOutlined,
  MoreOutlined,
  NodeIndexOutlined,
  PlusOutlined,
  ReloadOutlined,
  RightOutlined,
  SafetyCertificateOutlined,
  SaveOutlined,
  SearchOutlined,
  SettingOutlined,
  SkinOutlined,
  SmileOutlined,
  SwapOutlined,
  SyncOutlined,
  TeamOutlined,
  UndoOutlined,
  UpOutlined,
  UserAddOutlined,
  UserOutlined,
  WechatFilled,
  WifiOutlined,
} from '@ant-design/icons';
import type { FC } from 'react';

export type IconConfig =
  | { type: 'antd'; component: FC<any> }
  | { type: 'lucide'; component: FC<any> }
  | { type: 'sprite'; symbol: string }
  | { type: 'svg'; component: FC<any> };

function defineIcons<T extends Record<string, IconConfig>>(map: T) {
  return map;
}

const SPRITE_PREFIX = 'gvray-' as const;
const sv = (name: string) => `${SPRITE_PREFIX}${name}` as const;

/** 图标白名单 —— 项目中实际使用到的图标（运行时核心集合） */
export const iconMap: Record<string, IconConfig> = defineIcons({
  AlipayCircleFilled: { type: 'antd', component: AlipayCircleFilled },
  ApiOutlined: { type: 'antd', component: ApiOutlined },
  ArrowDownOutlined: { type: 'antd', component: ArrowDownOutlined },
  ArrowLeftOutlined: { type: 'antd', component: ArrowLeftOutlined },
  ArrowUpOutlined: { type: 'antd', component: ArrowUpOutlined },
  BellOutlined: { type: 'antd', component: BellOutlined },
  BugOutlined: { type: 'antd', component: BugOutlined },
  CheckCircleFilled: { type: 'antd', component: CheckCircleFilled },
  CheckCircleOutlined: { type: 'antd', component: CheckCircleOutlined },
  CheckOutlined: { type: 'antd', component: CheckOutlined },
  ClockCircleOutlined: { type: 'antd', component: ClockCircleOutlined },
  CloseCircleFilled: { type: 'antd', component: CloseCircleFilled },
  CloseCircleOutlined: { type: 'antd', component: CloseCircleOutlined },
  CloseOutlined: { type: 'antd', component: CloseOutlined },
  CopyOutlined: { type: 'antd', component: CopyOutlined },
  DashboardOutlined: { type: 'antd', component: DashboardOutlined },
  DatabaseOutlined: { type: 'antd', component: DatabaseOutlined },
  DeleteOutlined: { type: 'antd', component: DeleteOutlined },
  DownOutlined: { type: 'antd', component: DownOutlined },
  EditOutlined: { type: 'antd', component: EditOutlined },
  ExclamationCircleFilled: { type: 'antd', component: ExclamationCircleFilled },
  ExclamationCircleOutlined: {
    type: 'antd',
    component: ExclamationCircleOutlined,
  },
  EyeInvisibleOutlined: { type: 'antd', component: EyeInvisibleOutlined },
  EyeOutlined: { type: 'antd', component: EyeOutlined },
  EyeTwoTone: { type: 'antd', component: EyeTwoTone },
  FieldTimeOutlined: { type: 'antd', component: FieldTimeOutlined },
  FileTextOutlined: { type: 'antd', component: FileTextOutlined },
  FolderOutlined: { type: 'antd', component: FolderOutlined },
  GithubFilled: { type: 'antd', component: GithubFilled },
  HistoryOutlined: { type: 'antd', component: HistoryOutlined },
  HomeOutlined: { type: 'antd', component: HomeOutlined },
  IdcardOutlined: { type: 'antd', component: IdcardOutlined },
  InfoCircleOutlined: { type: 'antd', component: InfoCircleOutlined },
  KeyOutlined: { type: 'antd', component: KeyOutlined },
  LayoutOutlined: { type: 'antd', component: LayoutOutlined },
  LeftOutlined: { type: 'antd', component: LeftOutlined },
  LockOutlined: { type: 'antd', component: LockOutlined },
  LoginOutlined: { type: 'antd', component: LoginOutlined },
  MailOutlined: { type: 'antd', component: MailOutlined },
  MobileOutlined: { type: 'antd', component: MobileOutlined },
  MoreOutlined: { type: 'antd', component: MoreOutlined },
  NodeIndexOutlined: { type: 'antd', component: NodeIndexOutlined },
  PlusOutlined: { type: 'antd', component: PlusOutlined },
  ReloadOutlined: { type: 'antd', component: ReloadOutlined },
  RightOutlined: { type: 'antd', component: RightOutlined },
  SafetyCertificateOutlined: {
    type: 'antd',
    component: SafetyCertificateOutlined,
  },
  SaveOutlined: { type: 'antd', component: SaveOutlined },
  SearchOutlined: { type: 'antd', component: SearchOutlined },
  SettingOutlined: { type: 'antd', component: SettingOutlined },
  SkinOutlined: { type: 'antd', component: SkinOutlined },
  SmileOutlined: { type: 'antd', component: SmileOutlined },
  SwapOutlined: { type: 'antd', component: SwapOutlined },
  SyncOutlined: { type: 'antd', component: SyncOutlined },
  TeamOutlined: { type: 'antd', component: TeamOutlined },
  UndoOutlined: { type: 'antd', component: UndoOutlined },
  UpOutlined: { type: 'antd', component: UpOutlined },
  UserAddOutlined: { type: 'antd', component: UserAddOutlined },
  UserOutlined: { type: 'antd', component: UserOutlined },
  WechatFilled: { type: 'antd', component: WechatFilled },
  WifiOutlined: { type: 'antd', component: WifiOutlined },
  'gvray-language': { type: 'sprite', symbol: sv('language') },
  'gvray-notification': { type: 'sprite', symbol: sv('notification') },
  'gvray-theme-primary': { type: 'sprite', symbol: sv('theme-primary') },
  'gvray-theme-light': { type: 'sprite', symbol: sv('theme-light') },
  'gvray-theme-dark': { type: 'sprite', symbol: sv('theme-dark') },
  'gvray-theme-system': { type: 'sprite', symbol: sv('theme-system') },
});
