import {
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayCircleFilled,
  AlipayCircleOutlined,
  AlipayOutlined,
  AliwangwangOutlined,
  AliyunOutlined,
  AmazonOutlined,
  AndroidOutlined,
  AntCloudOutlined,
  AntDesignOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppleOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowsAltOutlined,
  AudioMutedOutlined,
  AudioOutlined,
  AuditOutlined,
  BackwardOutlined,
  BaiduOutlined,
  BankOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  BellOutlined,
  BgColorsOutlined,
  BilibiliOutlined,
  BlockOutlined,
  BoldOutlined,
  BookOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderLeftOutlined,
  BorderOuterOutlined,
  BorderOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  BorderlessTableOutlined,
  BoxPlotOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  CarryOutOutlined,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckOutlined,
  CheckSquareOutlined,
  ChromeOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  ClockCircleOutlined,
  CloseCircleFilled,
  CloseCircleOutlined,
  CloseOutlined,
  CloseSquareOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CodeSandboxOutlined,
  CodepenCircleOutlined,
  CodepenOutlined,
  CoffeeOutlined,
  ColumnHeightOutlined,
  ColumnWidthOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyOutlined,
  CopyrightCircleOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffOutlined,
  DingdingOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DiscordOutlined,
  DislikeOutlined,
  DockerOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DotChartOutlined,
  DotNetOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  DownCircleOutlined,
  DownOutlined,
  DownSquareOutlined,
  DownloadOutlined,
  DragOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  DropboxOutlined,
  EditOutlined,
  EllipsisOutlined,
  EnterOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExclamationCircleFilled,
  ExclamationCircleOutlined,
  ExclamationOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  EyeTwoTone,
  FacebookOutlined,
  FallOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FileOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FolderViewOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  ForkOutlined,
  FormOutlined,
  FormatPainterOutlined,
  ForwardOutlined,
  FrownOutlined,
  FullscreenExitOutlined,
  FullscreenOutlined,
  FunctionOutlined,
  FundOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GithubFilled,
  GithubOutlined,
  GitlabOutlined,
  GlobalOutlined,
  GoldOutlined,
  GoogleOutlined,
  GooglePlusOutlined,
  GroupOutlined,
  HarmonyOSOutlined,
  HddOutlined,
  HeartOutlined,
  HeatMapOutlined,
  HighlightOutlined,
  HistoryOutlined,
  HolderOutlined,
  HomeOutlined,
  HourglassOutlined,
  Html5Outlined,
  IdcardOutlined,
  IeOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  InfoOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InstagramOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  IssuesCloseOutlined,
  ItalicOutlined,
  JavaOutlined,
  JavaScriptOutlined,
  KeyOutlined,
  KubernetesOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LeftCircleOutlined,
  LeftOutlined,
  LeftSquareOutlined,
  LikeOutlined,
  LineChartOutlined,
  LineHeightOutlined,
  LineOutlined,
  LinkOutlined,
  LinkedinOutlined,
  LinuxOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  LoginOutlined,
  LogoutOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MediumOutlined,
  MediumWorkmarkOutlined,
  MehOutlined,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MergeCellsOutlined,
  MergeOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  MinusOutlined,
  MinusSquareOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoonOutlined,
  MoreOutlined,
  MutedOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  OpenAIOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PauseCircleOutlined,
  PauseOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  PictureOutlined,
  PieChartOutlined,
  PinterestOutlined,
  PlayCircleOutlined,
  PlaySquareOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProductOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  PythonOutlined,
  QqOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  QuestionOutlined,
  RadarChartOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusSettingOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  RedditOutlined,
  RedoOutlined,
  ReloadOutlined,
  RestOutlined,
  RetweetOutlined,
  RightCircleOutlined,
  RightOutlined,
  RightSquareOutlined,
  RiseOutlined,
  RobotOutlined,
  RocketOutlined,
  RollbackOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  RubyOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  ScissorOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  ShrinkOutlined,
  SignatureOutlined,
  SisternodeOutlined,
  SketchOutlined,
  SkinOutlined,
  SkypeOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  SlidersOutlined,
  SmallDashOutlined,
  SmileOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  SpotifyOutlined,
  StarOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
  StockOutlined,
  StopOutlined,
  StrikethroughOutlined,
  SubnodeOutlined,
  SunOutlined,
  SwapLeftOutlined,
  SwapOutlined,
  SwapRightOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TaobaoCircleOutlined,
  TaobaoOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  TikTokOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  TruckOutlined,
  TwitchOutlined,
  TwitterOutlined,
  UnderlineOutlined,
  UndoOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UnorderedListOutlined,
  UpCircleOutlined,
  UpOutlined,
  UpSquareOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VerticalAlignBottomOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignTopOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WarningOutlined,
  WechatFilled,
  WechatOutlined,
  WechatWorkOutlined,
  WeiboCircleOutlined,
  WeiboOutlined,
  WeiboSquareOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WindowsOutlined,
  WomanOutlined,
  XOutlined,
  YahooOutlined,
  YoutubeOutlined,
  YuqueOutlined,
  ZhihuOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
} from '@ant-design/icons';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Bookmark,
  MapPin,
  TrendingUp,
} from 'lucide-react';
import type { FC } from 'react';
import { OnlineIcon, PermissionIcon, RoleIcon, UserIcon } from './svgs';

export type IconConfig =
  | { type: 'antd'; component: FC<any> }
  | { type: 'lucide'; component: FC<any> }
  | { type: 'sprite'; symbol: string }
  | { type: 'svg'; component: FC<any> };

function defineIcons<T extends Record<string, IconConfig>>(map: T) {
  return map;
}

const SPRITE_PREFIX = 'gvray-' as const;
const sv = (name: string) => `${SPRITE_PREFIX}${name}` as const;

export const iconMap = defineIcons({
  // ── antd Outlined ──
  AccountBookOutlined: { type: 'antd', component: AccountBookOutlined },
  AimOutlined: { type: 'antd', component: AimOutlined },
  AlertOutlined: { type: 'antd', component: AlertOutlined },
  AlibabaOutlined: { type: 'antd', component: AlibabaOutlined },
  AlignCenterOutlined: { type: 'antd', component: AlignCenterOutlined },
  AlignLeftOutlined: { type: 'antd', component: AlignLeftOutlined },
  AlignRightOutlined: { type: 'antd', component: AlignRightOutlined },
  AlipayCircleOutlined: { type: 'antd', component: AlipayCircleOutlined },
  AlipayOutlined: { type: 'antd', component: AlipayOutlined },
  AliwangwangOutlined: { type: 'antd', component: AliwangwangOutlined },
  AliyunOutlined: { type: 'antd', component: AliyunOutlined },
  AmazonOutlined: { type: 'antd', component: AmazonOutlined },
  AndroidOutlined: { type: 'antd', component: AndroidOutlined },
  AntCloudOutlined: { type: 'antd', component: AntCloudOutlined },
  AntDesignOutlined: { type: 'antd', component: AntDesignOutlined },
  ApartmentOutlined: { type: 'antd', component: ApartmentOutlined },
  ApiOutlined: { type: 'antd', component: ApiOutlined },
  AppleOutlined: { type: 'antd', component: AppleOutlined },
  AppstoreAddOutlined: { type: 'antd', component: AppstoreAddOutlined },
  AppstoreOutlined: { type: 'antd', component: AppstoreOutlined },
  AreaChartOutlined: { type: 'antd', component: AreaChartOutlined },
  ArrowDownOutlined: { type: 'antd', component: ArrowDownOutlined },
  ArrowLeftOutlined: { type: 'antd', component: ArrowLeftOutlined },
  ArrowRightOutlined: { type: 'antd', component: ArrowRightOutlined },
  ArrowUpOutlined: { type: 'antd', component: ArrowUpOutlined },
  ArrowsAltOutlined: { type: 'antd', component: ArrowsAltOutlined },
  AudioMutedOutlined: { type: 'antd', component: AudioMutedOutlined },
  AudioOutlined: { type: 'antd', component: AudioOutlined },
  AuditOutlined: { type: 'antd', component: AuditOutlined },
  BackwardOutlined: { type: 'antd', component: BackwardOutlined },
  BaiduOutlined: { type: 'antd', component: BaiduOutlined },
  BankOutlined: { type: 'antd', component: BankOutlined },
  BarChartOutlined: { type: 'antd', component: BarChartOutlined },
  BarcodeOutlined: { type: 'antd', component: BarcodeOutlined },
  BarsOutlined: { type: 'antd', component: BarsOutlined },
  BehanceOutlined: { type: 'antd', component: BehanceOutlined },
  BehanceSquareOutlined: { type: 'antd', component: BehanceSquareOutlined },
  BellOutlined: { type: 'antd', component: BellOutlined },
  BgColorsOutlined: { type: 'antd', component: BgColorsOutlined },
  BilibiliOutlined: { type: 'antd', component: BilibiliOutlined },
  BlockOutlined: { type: 'antd', component: BlockOutlined },
  BoldOutlined: { type: 'antd', component: BoldOutlined },
  BookOutlined: { type: 'antd', component: BookOutlined },
  BorderBottomOutlined: { type: 'antd', component: BorderBottomOutlined },
  BorderHorizontalOutlined: {
    type: 'antd',
    component: BorderHorizontalOutlined,
  },
  BorderInnerOutlined: { type: 'antd', component: BorderInnerOutlined },
  BorderLeftOutlined: { type: 'antd', component: BorderLeftOutlined },
  BorderOuterOutlined: { type: 'antd', component: BorderOuterOutlined },
  BorderOutlined: { type: 'antd', component: BorderOutlined },
  BorderRightOutlined: { type: 'antd', component: BorderRightOutlined },
  BorderTopOutlined: { type: 'antd', component: BorderTopOutlined },
  BorderVerticleOutlined: { type: 'antd', component: BorderVerticleOutlined },
  BorderlessTableOutlined: { type: 'antd', component: BorderlessTableOutlined },
  BoxPlotOutlined: { type: 'antd', component: BoxPlotOutlined },
  BranchesOutlined: { type: 'antd', component: BranchesOutlined },
  BugOutlined: { type: 'antd', component: BugOutlined },
  BuildOutlined: { type: 'antd', component: BuildOutlined },
  BulbOutlined: { type: 'antd', component: BulbOutlined },
  CalculatorOutlined: { type: 'antd', component: CalculatorOutlined },
  CalendarOutlined: { type: 'antd', component: CalendarOutlined },
  CameraOutlined: { type: 'antd', component: CameraOutlined },
  CarOutlined: { type: 'antd', component: CarOutlined },
  CaretDownOutlined: { type: 'antd', component: CaretDownOutlined },
  CaretLeftOutlined: { type: 'antd', component: CaretLeftOutlined },
  CaretRightOutlined: { type: 'antd', component: CaretRightOutlined },
  CaretUpOutlined: { type: 'antd', component: CaretUpOutlined },
  CarryOutOutlined: { type: 'antd', component: CarryOutOutlined },
  CheckCircleOutlined: { type: 'antd', component: CheckCircleOutlined },
  CheckOutlined: { type: 'antd', component: CheckOutlined },
  CheckSquareOutlined: { type: 'antd', component: CheckSquareOutlined },
  ChromeOutlined: { type: 'antd', component: ChromeOutlined },
  CiCircleOutlined: { type: 'antd', component: CiCircleOutlined },
  CiOutlined: { type: 'antd', component: CiOutlined },
  ClearOutlined: { type: 'antd', component: ClearOutlined },
  ClockCircleOutlined: { type: 'antd', component: ClockCircleOutlined },
  CloseCircleOutlined: { type: 'antd', component: CloseCircleOutlined },
  CloseOutlined: { type: 'antd', component: CloseOutlined },
  CloseSquareOutlined: { type: 'antd', component: CloseSquareOutlined },
  CloudDownloadOutlined: { type: 'antd', component: CloudDownloadOutlined },
  CloudOutlined: { type: 'antd', component: CloudOutlined },
  CloudServerOutlined: { type: 'antd', component: CloudServerOutlined },
  CloudSyncOutlined: { type: 'antd', component: CloudSyncOutlined },
  CloudUploadOutlined: { type: 'antd', component: CloudUploadOutlined },
  ClusterOutlined: { type: 'antd', component: ClusterOutlined },
  CodeOutlined: { type: 'antd', component: CodeOutlined },
  CodeSandboxOutlined: { type: 'antd', component: CodeSandboxOutlined },
  CodepenCircleOutlined: { type: 'antd', component: CodepenCircleOutlined },
  CodepenOutlined: { type: 'antd', component: CodepenOutlined },
  CoffeeOutlined: { type: 'antd', component: CoffeeOutlined },
  ColumnHeightOutlined: { type: 'antd', component: ColumnHeightOutlined },
  ColumnWidthOutlined: { type: 'antd', component: ColumnWidthOutlined },
  CommentOutlined: { type: 'antd', component: CommentOutlined },
  CompassOutlined: { type: 'antd', component: CompassOutlined },
  CompressOutlined: { type: 'antd', component: CompressOutlined },
  ConsoleSqlOutlined: { type: 'antd', component: ConsoleSqlOutlined },
  ContactsOutlined: { type: 'antd', component: ContactsOutlined },
  ContainerOutlined: { type: 'antd', component: ContainerOutlined },
  ControlOutlined: { type: 'antd', component: ControlOutlined },
  CopyOutlined: { type: 'antd', component: CopyOutlined },
  CopyrightCircleOutlined: { type: 'antd', component: CopyrightCircleOutlined },
  CopyrightOutlined: { type: 'antd', component: CopyrightOutlined },
  CreditCardOutlined: { type: 'antd', component: CreditCardOutlined },
  CrownOutlined: { type: 'antd', component: CrownOutlined },
  CustomerServiceOutlined: { type: 'antd', component: CustomerServiceOutlined },
  DashOutlined: { type: 'antd', component: DashOutlined },
  DashboardOutlined: { type: 'antd', component: DashboardOutlined },
  DatabaseOutlined: { type: 'antd', component: DatabaseOutlined },
  DeleteColumnOutlined: { type: 'antd', component: DeleteColumnOutlined },
  DeleteOutlined: { type: 'antd', component: DeleteOutlined },
  DeleteRowOutlined: { type: 'antd', component: DeleteRowOutlined },
  DeliveredProcedureOutlined: {
    type: 'antd',
    component: DeliveredProcedureOutlined,
  },
  DeploymentUnitOutlined: { type: 'antd', component: DeploymentUnitOutlined },
  DesktopOutlined: { type: 'antd', component: DesktopOutlined },
  DiffOutlined: { type: 'antd', component: DiffOutlined },
  DingdingOutlined: { type: 'antd', component: DingdingOutlined },
  DingtalkOutlined: { type: 'antd', component: DingtalkOutlined },
  DisconnectOutlined: { type: 'antd', component: DisconnectOutlined },
  DiscordOutlined: { type: 'antd', component: DiscordOutlined },
  DislikeOutlined: { type: 'antd', component: DislikeOutlined },
  DockerOutlined: { type: 'antd', component: DockerOutlined },
  DollarCircleOutlined: { type: 'antd', component: DollarCircleOutlined },
  DollarOutlined: { type: 'antd', component: DollarOutlined },
  DotChartOutlined: { type: 'antd', component: DotChartOutlined },
  DotNetOutlined: { type: 'antd', component: DotNetOutlined },
  DoubleLeftOutlined: { type: 'antd', component: DoubleLeftOutlined },
  DoubleRightOutlined: { type: 'antd', component: DoubleRightOutlined },
  DownCircleOutlined: { type: 'antd', component: DownCircleOutlined },
  DownOutlined: { type: 'antd', component: DownOutlined },
  DownSquareOutlined: { type: 'antd', component: DownSquareOutlined },
  DownloadOutlined: { type: 'antd', component: DownloadOutlined },
  DragOutlined: { type: 'antd', component: DragOutlined },
  DribbbleOutlined: { type: 'antd', component: DribbbleOutlined },
  DribbbleSquareOutlined: { type: 'antd', component: DribbbleSquareOutlined },
  DropboxOutlined: { type: 'antd', component: DropboxOutlined },
  EditOutlined: { type: 'antd', component: EditOutlined },
  EllipsisOutlined: { type: 'antd', component: EllipsisOutlined },
  EnterOutlined: { type: 'antd', component: EnterOutlined },
  EnvironmentOutlined: { type: 'antd', component: EnvironmentOutlined },
  EuroCircleOutlined: { type: 'antd', component: EuroCircleOutlined },
  EuroOutlined: { type: 'antd', component: EuroOutlined },
  ExceptionOutlined: { type: 'antd', component: ExceptionOutlined },
  ExclamationCircleOutlined: {
    type: 'antd',
    component: ExclamationCircleOutlined,
  },
  ExclamationOutlined: { type: 'antd', component: ExclamationOutlined },
  ExpandAltOutlined: { type: 'antd', component: ExpandAltOutlined },
  ExpandOutlined: { type: 'antd', component: ExpandOutlined },
  ExperimentOutlined: { type: 'antd', component: ExperimentOutlined },
  ExportOutlined: { type: 'antd', component: ExportOutlined },
  EyeInvisibleOutlined: { type: 'antd', component: EyeInvisibleOutlined },
  EyeOutlined: { type: 'antd', component: EyeOutlined },
  EyeTwoTone: { type: 'antd', component: EyeTwoTone },
  FacebookOutlined: { type: 'antd', component: FacebookOutlined },
  FallOutlined: { type: 'antd', component: FallOutlined },
  FastBackwardOutlined: { type: 'antd', component: FastBackwardOutlined },
  FastForwardOutlined: { type: 'antd', component: FastForwardOutlined },
  FieldBinaryOutlined: { type: 'antd', component: FieldBinaryOutlined },
  FieldNumberOutlined: { type: 'antd', component: FieldNumberOutlined },
  FieldStringOutlined: { type: 'antd', component: FieldStringOutlined },
  FieldTimeOutlined: { type: 'antd', component: FieldTimeOutlined },
  FileAddOutlined: { type: 'antd', component: FileAddOutlined },
  FileDoneOutlined: { type: 'antd', component: FileDoneOutlined },
  FileExcelOutlined: { type: 'antd', component: FileExcelOutlined },
  FileExclamationOutlined: { type: 'antd', component: FileExclamationOutlined },
  FileGifOutlined: { type: 'antd', component: FileGifOutlined },
  FileImageOutlined: { type: 'antd', component: FileImageOutlined },
  FileJpgOutlined: { type: 'antd', component: FileJpgOutlined },
  FileMarkdownOutlined: { type: 'antd', component: FileMarkdownOutlined },
  FileOutlined: { type: 'antd', component: FileOutlined },
  FilePdfOutlined: { type: 'antd', component: FilePdfOutlined },
  FilePptOutlined: { type: 'antd', component: FilePptOutlined },
  FileProtectOutlined: { type: 'antd', component: FileProtectOutlined },
  FileSearchOutlined: { type: 'antd', component: FileSearchOutlined },
  FileSyncOutlined: { type: 'antd', component: FileSyncOutlined },
  FileTextOutlined: { type: 'antd', component: FileTextOutlined },
  FileUnknownOutlined: { type: 'antd', component: FileUnknownOutlined },
  FileWordOutlined: { type: 'antd', component: FileWordOutlined },
  FileZipOutlined: { type: 'antd', component: FileZipOutlined },
  FilterOutlined: { type: 'antd', component: FilterOutlined },
  FireOutlined: { type: 'antd', component: FireOutlined },
  FlagOutlined: { type: 'antd', component: FlagOutlined },
  FolderAddOutlined: { type: 'antd', component: FolderAddOutlined },
  FolderOpenOutlined: { type: 'antd', component: FolderOpenOutlined },
  FolderOutlined: { type: 'antd', component: FolderOutlined },
  FolderViewOutlined: { type: 'antd', component: FolderViewOutlined },
  FontColorsOutlined: { type: 'antd', component: FontColorsOutlined },
  FontSizeOutlined: { type: 'antd', component: FontSizeOutlined },
  ForkOutlined: { type: 'antd', component: ForkOutlined },
  FormOutlined: { type: 'antd', component: FormOutlined },
  FormatPainterOutlined: { type: 'antd', component: FormatPainterOutlined },
  ForwardOutlined: { type: 'antd', component: ForwardOutlined },
  FrownOutlined: { type: 'antd', component: FrownOutlined },
  FullscreenExitOutlined: { type: 'antd', component: FullscreenExitOutlined },
  FullscreenOutlined: { type: 'antd', component: FullscreenOutlined },
  FunctionOutlined: { type: 'antd', component: FunctionOutlined },
  FundOutlined: { type: 'antd', component: FundOutlined },
  FundProjectionScreenOutlined: {
    type: 'antd',
    component: FundProjectionScreenOutlined,
  },
  FundViewOutlined: { type: 'antd', component: FundViewOutlined },
  FunnelPlotOutlined: { type: 'antd', component: FunnelPlotOutlined },
  GatewayOutlined: { type: 'antd', component: GatewayOutlined },
  GifOutlined: { type: 'antd', component: GifOutlined },
  GiftOutlined: { type: 'antd', component: GiftOutlined },
  GithubOutlined: { type: 'antd', component: GithubOutlined },
  GitlabOutlined: { type: 'antd', component: GitlabOutlined },
  GlobalOutlined: { type: 'antd', component: GlobalOutlined },
  GoldOutlined: { type: 'antd', component: GoldOutlined },
  GoogleOutlined: { type: 'antd', component: GoogleOutlined },
  GooglePlusOutlined: { type: 'antd', component: GooglePlusOutlined },
  GroupOutlined: { type: 'antd', component: GroupOutlined },
  HarmonyOSOutlined: { type: 'antd', component: HarmonyOSOutlined },
  HddOutlined: { type: 'antd', component: HddOutlined },
  HeartOutlined: { type: 'antd', component: HeartOutlined },
  HeatMapOutlined: { type: 'antd', component: HeatMapOutlined },
  HighlightOutlined: { type: 'antd', component: HighlightOutlined },
  HistoryOutlined: { type: 'antd', component: HistoryOutlined },
  HolderOutlined: { type: 'antd', component: HolderOutlined },
  HomeOutlined: { type: 'antd', component: HomeOutlined },
  HourglassOutlined: { type: 'antd', component: HourglassOutlined },
  Html5Outlined: { type: 'antd', component: Html5Outlined },
  IdcardOutlined: { type: 'antd', component: IdcardOutlined },
  IeOutlined: { type: 'antd', component: IeOutlined },
  ImportOutlined: { type: 'antd', component: ImportOutlined },
  InboxOutlined: { type: 'antd', component: InboxOutlined },
  InfoCircleOutlined: { type: 'antd', component: InfoCircleOutlined },
  InfoOutlined: { type: 'antd', component: InfoOutlined },
  InsertRowAboveOutlined: { type: 'antd', component: InsertRowAboveOutlined },
  InsertRowBelowOutlined: { type: 'antd', component: InsertRowBelowOutlined },
  InsertRowLeftOutlined: { type: 'antd', component: InsertRowLeftOutlined },
  InsertRowRightOutlined: { type: 'antd', component: InsertRowRightOutlined },
  InstagramOutlined: { type: 'antd', component: InstagramOutlined },
  InsuranceOutlined: { type: 'antd', component: InsuranceOutlined },
  InteractionOutlined: { type: 'antd', component: InteractionOutlined },
  IssuesCloseOutlined: { type: 'antd', component: IssuesCloseOutlined },
  ItalicOutlined: { type: 'antd', component: ItalicOutlined },
  JavaOutlined: { type: 'antd', component: JavaOutlined },
  JavaScriptOutlined: { type: 'antd', component: JavaScriptOutlined },
  KeyOutlined: { type: 'antd', component: KeyOutlined },
  KubernetesOutlined: { type: 'antd', component: KubernetesOutlined },
  LaptopOutlined: { type: 'antd', component: LaptopOutlined },
  LayoutOutlined: { type: 'antd', component: LayoutOutlined },
  LeftCircleOutlined: { type: 'antd', component: LeftCircleOutlined },
  LeftOutlined: { type: 'antd', component: LeftOutlined },
  LeftSquareOutlined: { type: 'antd', component: LeftSquareOutlined },
  LikeOutlined: { type: 'antd', component: LikeOutlined },
  LineChartOutlined: { type: 'antd', component: LineChartOutlined },
  LineHeightOutlined: { type: 'antd', component: LineHeightOutlined },
  LineOutlined: { type: 'antd', component: LineOutlined },
  LinkOutlined: { type: 'antd', component: LinkOutlined },
  LinkedinOutlined: { type: 'antd', component: LinkedinOutlined },
  LinuxOutlined: { type: 'antd', component: LinuxOutlined },
  Loading3QuartersOutlined: {
    type: 'antd',
    component: Loading3QuartersOutlined,
  },
  LoadingOutlined: { type: 'antd', component: LoadingOutlined },
  LockOutlined: { type: 'antd', component: LockOutlined },
  LoginOutlined: { type: 'antd', component: LoginOutlined },
  LogoutOutlined: { type: 'antd', component: LogoutOutlined },
  MacCommandOutlined: { type: 'antd', component: MacCommandOutlined },
  MailOutlined: { type: 'antd', component: MailOutlined },
  ManOutlined: { type: 'antd', component: ManOutlined },
  MedicineBoxOutlined: { type: 'antd', component: MedicineBoxOutlined },
  MediumOutlined: { type: 'antd', component: MediumOutlined },
  MediumWorkmarkOutlined: { type: 'antd', component: MediumWorkmarkOutlined },
  MehOutlined: { type: 'antd', component: MehOutlined },
  MenuFoldOutlined: { type: 'antd', component: MenuFoldOutlined },
  MenuOutlined: { type: 'antd', component: MenuOutlined },
  MenuUnfoldOutlined: { type: 'antd', component: MenuUnfoldOutlined },
  MergeCellsOutlined: { type: 'antd', component: MergeCellsOutlined },
  MergeOutlined: { type: 'antd', component: MergeOutlined },
  MessageOutlined: { type: 'antd', component: MessageOutlined },
  MinusCircleOutlined: { type: 'antd', component: MinusCircleOutlined },
  MinusOutlined: { type: 'antd', component: MinusOutlined },
  MinusSquareOutlined: { type: 'antd', component: MinusSquareOutlined },
  MobileOutlined: { type: 'antd', component: MobileOutlined },
  MoneyCollectOutlined: { type: 'antd', component: MoneyCollectOutlined },
  MonitorOutlined: { type: 'antd', component: MonitorOutlined },
  MoonOutlined: { type: 'antd', component: MoonOutlined },
  MoreOutlined: { type: 'antd', component: MoreOutlined },
  MutedOutlined: { type: 'antd', component: MutedOutlined },
  NodeCollapseOutlined: { type: 'antd', component: NodeCollapseOutlined },
  NodeExpandOutlined: { type: 'antd', component: NodeExpandOutlined },
  NodeIndexOutlined: { type: 'antd', component: NodeIndexOutlined },
  NotificationOutlined: { type: 'antd', component: NotificationOutlined },
  NumberOutlined: { type: 'antd', component: NumberOutlined },
  OneToOneOutlined: { type: 'antd', component: OneToOneOutlined },
  OpenAIOutlined: { type: 'antd', component: OpenAIOutlined },
  OrderedListOutlined: { type: 'antd', component: OrderedListOutlined },
  PaperClipOutlined: { type: 'antd', component: PaperClipOutlined },
  PartitionOutlined: { type: 'antd', component: PartitionOutlined },
  PauseCircleOutlined: { type: 'antd', component: PauseCircleOutlined },
  PauseOutlined: { type: 'antd', component: PauseOutlined },
  PayCircleOutlined: { type: 'antd', component: PayCircleOutlined },
  PercentageOutlined: { type: 'antd', component: PercentageOutlined },
  PhoneOutlined: { type: 'antd', component: PhoneOutlined },
  PicCenterOutlined: { type: 'antd', component: PicCenterOutlined },
  PicLeftOutlined: { type: 'antd', component: PicLeftOutlined },
  PicRightOutlined: { type: 'antd', component: PicRightOutlined },
  PictureOutlined: { type: 'antd', component: PictureOutlined },
  PieChartOutlined: { type: 'antd', component: PieChartOutlined },
  PinterestOutlined: { type: 'antd', component: PinterestOutlined },
  PlayCircleOutlined: { type: 'antd', component: PlayCircleOutlined },
  PlaySquareOutlined: { type: 'antd', component: PlaySquareOutlined },
  PlusCircleOutlined: { type: 'antd', component: PlusCircleOutlined },
  PlusOutlined: { type: 'antd', component: PlusOutlined },
  PlusSquareOutlined: { type: 'antd', component: PlusSquareOutlined },
  PoundCircleOutlined: { type: 'antd', component: PoundCircleOutlined },
  PoundOutlined: { type: 'antd', component: PoundOutlined },
  PoweroffOutlined: { type: 'antd', component: PoweroffOutlined },
  PrinterOutlined: { type: 'antd', component: PrinterOutlined },
  ProductOutlined: { type: 'antd', component: ProductOutlined },
  ProfileOutlined: { type: 'antd', component: ProfileOutlined },
  ProjectOutlined: { type: 'antd', component: ProjectOutlined },
  PropertySafetyOutlined: { type: 'antd', component: PropertySafetyOutlined },
  PullRequestOutlined: { type: 'antd', component: PullRequestOutlined },
  PushpinOutlined: { type: 'antd', component: PushpinOutlined },
  PythonOutlined: { type: 'antd', component: PythonOutlined },
  QqOutlined: { type: 'antd', component: QqOutlined },
  QrcodeOutlined: { type: 'antd', component: QrcodeOutlined },
  QuestionCircleOutlined: { type: 'antd', component: QuestionCircleOutlined },
  QuestionOutlined: { type: 'antd', component: QuestionOutlined },
  RadarChartOutlined: { type: 'antd', component: RadarChartOutlined },
  RadiusBottomleftOutlined: {
    type: 'antd',
    component: RadiusBottomleftOutlined,
  },
  RadiusBottomrightOutlined: {
    type: 'antd',
    component: RadiusBottomrightOutlined,
  },
  RadiusSettingOutlined: { type: 'antd', component: RadiusSettingOutlined },
  RadiusUpleftOutlined: { type: 'antd', component: RadiusUpleftOutlined },
  RadiusUprightOutlined: { type: 'antd', component: RadiusUprightOutlined },
  ReadOutlined: { type: 'antd', component: ReadOutlined },
  ReconciliationOutlined: { type: 'antd', component: ReconciliationOutlined },
  RedEnvelopeOutlined: { type: 'antd', component: RedEnvelopeOutlined },
  RedditOutlined: { type: 'antd', component: RedditOutlined },
  RedoOutlined: { type: 'antd', component: RedoOutlined },
  ReloadOutlined: { type: 'antd', component: ReloadOutlined },
  RestOutlined: { type: 'antd', component: RestOutlined },
  RetweetOutlined: { type: 'antd', component: RetweetOutlined },
  RightCircleOutlined: { type: 'antd', component: RightCircleOutlined },
  RightOutlined: { type: 'antd', component: RightOutlined },
  RightSquareOutlined: { type: 'antd', component: RightSquareOutlined },
  RiseOutlined: { type: 'antd', component: RiseOutlined },
  RobotOutlined: { type: 'antd', component: RobotOutlined },
  RocketOutlined: { type: 'antd', component: RocketOutlined },
  RollbackOutlined: { type: 'antd', component: RollbackOutlined },
  RotateLeftOutlined: { type: 'antd', component: RotateLeftOutlined },
  RotateRightOutlined: { type: 'antd', component: RotateRightOutlined },
  RubyOutlined: { type: 'antd', component: RubyOutlined },
  SafetyCertificateOutlined: {
    type: 'antd',
    component: SafetyCertificateOutlined,
  },
  SafetyOutlined: { type: 'antd', component: SafetyOutlined },
  SaveOutlined: { type: 'antd', component: SaveOutlined },
  ScanOutlined: { type: 'antd', component: ScanOutlined },
  ScheduleOutlined: { type: 'antd', component: ScheduleOutlined },
  ScissorOutlined: { type: 'antd', component: ScissorOutlined },
  SearchOutlined: { type: 'antd', component: SearchOutlined },
  SecurityScanOutlined: { type: 'antd', component: SecurityScanOutlined },
  SelectOutlined: { type: 'antd', component: SelectOutlined },
  SendOutlined: { type: 'antd', component: SendOutlined },
  SettingOutlined: { type: 'antd', component: SettingOutlined },
  ShakeOutlined: { type: 'antd', component: ShakeOutlined },
  ShareAltOutlined: { type: 'antd', component: ShareAltOutlined },
  ShopOutlined: { type: 'antd', component: ShopOutlined },
  ShoppingCartOutlined: { type: 'antd', component: ShoppingCartOutlined },
  ShoppingOutlined: { type: 'antd', component: ShoppingOutlined },
  ShrinkOutlined: { type: 'antd', component: ShrinkOutlined },
  SignatureOutlined: { type: 'antd', component: SignatureOutlined },
  SisternodeOutlined: { type: 'antd', component: SisternodeOutlined },
  SketchOutlined: { type: 'antd', component: SketchOutlined },
  SkinOutlined: { type: 'antd', component: SkinOutlined },
  SkypeOutlined: { type: 'antd', component: SkypeOutlined },
  SlackOutlined: { type: 'antd', component: SlackOutlined },
  SlackSquareOutlined: { type: 'antd', component: SlackSquareOutlined },
  SlidersOutlined: { type: 'antd', component: SlidersOutlined },
  SmallDashOutlined: { type: 'antd', component: SmallDashOutlined },
  SmileOutlined: { type: 'antd', component: SmileOutlined },
  SnippetsOutlined: { type: 'antd', component: SnippetsOutlined },
  SolutionOutlined: { type: 'antd', component: SolutionOutlined },
  SortAscendingOutlined: { type: 'antd', component: SortAscendingOutlined },
  SortDescendingOutlined: { type: 'antd', component: SortDescendingOutlined },
  SoundOutlined: { type: 'antd', component: SoundOutlined },
  SplitCellsOutlined: { type: 'antd', component: SplitCellsOutlined },
  SpotifyOutlined: { type: 'antd', component: SpotifyOutlined },
  StarOutlined: { type: 'antd', component: StarOutlined },
  StepBackwardOutlined: { type: 'antd', component: StepBackwardOutlined },
  StepForwardOutlined: { type: 'antd', component: StepForwardOutlined },
  StockOutlined: { type: 'antd', component: StockOutlined },
  StopOutlined: { type: 'antd', component: StopOutlined },
  StrikethroughOutlined: { type: 'antd', component: StrikethroughOutlined },
  SubnodeOutlined: { type: 'antd', component: SubnodeOutlined },
  SunOutlined: { type: 'antd', component: SunOutlined },
  SwapLeftOutlined: { type: 'antd', component: SwapLeftOutlined },
  SwapOutlined: { type: 'antd', component: SwapOutlined },
  SwapRightOutlined: { type: 'antd', component: SwapRightOutlined },
  SwitcherOutlined: { type: 'antd', component: SwitcherOutlined },
  SyncOutlined: { type: 'antd', component: SyncOutlined },
  TableOutlined: { type: 'antd', component: TableOutlined },
  TabletOutlined: { type: 'antd', component: TabletOutlined },
  TagOutlined: { type: 'antd', component: TagOutlined },
  TagsOutlined: { type: 'antd', component: TagsOutlined },
  TaobaoCircleOutlined: { type: 'antd', component: TaobaoCircleOutlined },
  TaobaoOutlined: { type: 'antd', component: TaobaoOutlined },
  TeamOutlined: { type: 'antd', component: TeamOutlined },
  ThunderboltOutlined: { type: 'antd', component: ThunderboltOutlined },
  TikTokOutlined: { type: 'antd', component: TikTokOutlined },
  ToTopOutlined: { type: 'antd', component: ToTopOutlined },
  ToolOutlined: { type: 'antd', component: ToolOutlined },
  TrademarkCircleOutlined: { type: 'antd', component: TrademarkCircleOutlined },
  TrademarkOutlined: { type: 'antd', component: TrademarkOutlined },
  TransactionOutlined: { type: 'antd', component: TransactionOutlined },
  TranslationOutlined: { type: 'antd', component: TranslationOutlined },
  TrophyOutlined: { type: 'antd', component: TrophyOutlined },
  TruckOutlined: { type: 'antd', component: TruckOutlined },
  TwitchOutlined: { type: 'antd', component: TwitchOutlined },
  TwitterOutlined: { type: 'antd', component: TwitterOutlined },
  UnderlineOutlined: { type: 'antd', component: UnderlineOutlined },
  UndoOutlined: { type: 'antd', component: UndoOutlined },
  UngroupOutlined: { type: 'antd', component: UngroupOutlined },
  UnlockOutlined: { type: 'antd', component: UnlockOutlined },
  UnorderedListOutlined: { type: 'antd', component: UnorderedListOutlined },
  UpCircleOutlined: { type: 'antd', component: UpCircleOutlined },
  UpOutlined: { type: 'antd', component: UpOutlined },
  UpSquareOutlined: { type: 'antd', component: UpSquareOutlined },
  UploadOutlined: { type: 'antd', component: UploadOutlined },
  UsbOutlined: { type: 'antd', component: UsbOutlined },
  UserAddOutlined: { type: 'antd', component: UserAddOutlined },
  UserDeleteOutlined: { type: 'antd', component: UserDeleteOutlined },
  UserOutlined: { type: 'antd', component: UserOutlined },
  UserSwitchOutlined: { type: 'antd', component: UserSwitchOutlined },
  UsergroupAddOutlined: { type: 'antd', component: UsergroupAddOutlined },
  UsergroupDeleteOutlined: { type: 'antd', component: UsergroupDeleteOutlined },
  VerifiedOutlined: { type: 'antd', component: VerifiedOutlined },
  VerticalAlignBottomOutlined: {
    type: 'antd',
    component: VerticalAlignBottomOutlined,
  },
  VerticalAlignMiddleOutlined: {
    type: 'antd',
    component: VerticalAlignMiddleOutlined,
  },
  VerticalAlignTopOutlined: {
    type: 'antd',
    component: VerticalAlignTopOutlined,
  },
  VerticalLeftOutlined: { type: 'antd', component: VerticalLeftOutlined },
  VerticalRightOutlined: { type: 'antd', component: VerticalRightOutlined },
  VideoCameraAddOutlined: { type: 'antd', component: VideoCameraAddOutlined },
  VideoCameraOutlined: { type: 'antd', component: VideoCameraOutlined },
  WalletOutlined: { type: 'antd', component: WalletOutlined },
  WarningOutlined: { type: 'antd', component: WarningOutlined },
  WechatOutlined: { type: 'antd', component: WechatOutlined },
  WechatWorkOutlined: { type: 'antd', component: WechatWorkOutlined },
  WeiboCircleOutlined: { type: 'antd', component: WeiboCircleOutlined },
  WeiboOutlined: { type: 'antd', component: WeiboOutlined },
  WeiboSquareOutlined: { type: 'antd', component: WeiboSquareOutlined },
  WhatsAppOutlined: { type: 'antd', component: WhatsAppOutlined },
  WifiOutlined: { type: 'antd', component: WifiOutlined },
  WindowsOutlined: { type: 'antd', component: WindowsOutlined },
  WomanOutlined: { type: 'antd', component: WomanOutlined },
  XOutlined: { type: 'antd', component: XOutlined },
  YahooOutlined: { type: 'antd', component: YahooOutlined },
  YoutubeOutlined: { type: 'antd', component: YoutubeOutlined },
  YuqueOutlined: { type: 'antd', component: YuqueOutlined },
  ZhihuOutlined: { type: 'antd', component: ZhihuOutlined },
  ZoomInOutlined: { type: 'antd', component: ZoomInOutlined },
  ZoomOutOutlined: { type: 'antd', component: ZoomOutOutlined },

  // ── antd Filled ──
  AlipayCircleFilled: { type: 'antd', component: AlipayCircleFilled },
  CheckCircleFilled: { type: 'antd', component: CheckCircleFilled },
  CloseCircleFilled: { type: 'antd', component: CloseCircleFilled },
  ExclamationCircleFilled: { type: 'antd', component: ExclamationCircleFilled },
  GithubFilled: { type: 'antd', component: GithubFilled },
  WechatFilled: { type: 'antd', component: WechatFilled },

  // ── custom SVG ──
  UserIcon: { type: 'svg', component: UserIcon },
  OnlineIcon: { type: 'svg', component: OnlineIcon },
  PermissionIcon: { type: 'svg', component: PermissionIcon },
  RoleIcon: { type: 'svg', component: RoleIcon },

  // ── lucide（仅 antd 没有的图标）──
  Activity: { type: 'lucide', component: Activity },
  AlertCircle: { type: 'lucide', component: AlertCircle },
  AlertTriangle: { type: 'lucide', component: AlertTriangle },
  BarChart3: { type: 'lucide', component: BarChart3 },
  Bookmark: { type: 'lucide', component: Bookmark },
  MapPin: { type: 'lucide', component: MapPin },
  TrendingUp: { type: 'lucide', component: TrendingUp },

  // ── sprite（iconfont Symbol）──
  [sv('notification')]: { type: 'sprite', symbol: sv('notification') },
  [sv('theme-dark')]: { type: 'sprite', symbol: sv('theme-dark') },
  [sv('theme-light')]: { type: 'sprite', symbol: sv('theme-light') },
  [sv('theme-primary')]: { type: 'sprite', symbol: sv('theme-primary') },
  [sv('theme-system')]: { type: 'sprite', symbol: sv('theme-system') },
  [sv('language')]: { type: 'sprite', symbol: sv('language') },
});

export type IconKey = keyof typeof iconMap;
